
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  pgsql:
    image: postgres:13
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdev:/var/lib/postgresql/data
    networks:
      - laravel

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - pgsql

volumes:
  dbdev:

networks:
  laravel:
    driver: bridge
